import { S3_IMAGE_BUCKET } from '../configs';
import { Project } from '../models';

export const projects: Project[] = [
  {
    id: '1',
    title: '제목',
    description: 'asdfasdf',
    period: 3,
    stacks: [1, 2, 3, 4],
    purpose: 'improvement',
    status: 'recruiting',
    leaderJob: 'backendDeveloper',
    recruitMember: {
      frontendDeveloper: 5,
      backendDeveloper: 5,
      designer: 5,
      productManager: 5,
    },
    bookMarkCount: 1,
    members: [
      {
        id: '347',
        email: 'asdf@asdf.com',
        nickname: 'asdf',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/arthur.svg`,
        provider: 'link-gather',
        type: 'leader',
      },
      {
        id: '874',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: '6708067',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: '7986867997',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'frontendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: '25345243',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'frontendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
    ],
  },
  {
    id: '12341234',
    title: '제목',
    description: 'asdfasdf',
    period: 3,
    stacks: [1, 2, 3, 4],
    purpose: 'fun',
    status: 'recruiting',
    leaderJob: 'backendDeveloper',
    recruitMember: {
      frontendDeveloper: 5,
      backendDeveloper: 5,
      designer: 5,
      productManager: 5,
    },
    bookMarkCount: 5,
    members: [
      {
        id: '2475',
        email: 'asdf@asdf.com',
        nickname: 'asdf',
        job: 'designer',
        profileImage: `${S3_IMAGE_BUCKET}/arthur.svg`,
        provider: 'link-gather',
        type: 'leader',
      },
      {
        id: '123856344',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'designer',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: '38566835',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'productManager',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: '27545247',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: '869867564',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'productManager',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
    ],
  },
  {
    id: '1345jip',
    title: '제목',
    description: 'asdfasdf',
    period: 3,
    stacks: [1, 2, 3, 4],
    purpose: 'study',
    status: 'recruiting',
    leaderJob: 'backendDeveloper',
    recruitMember: {
      frontendDeveloper: 5,
      backendDeveloper: 5,
      designer: 5,
      productManager: 5,
    },
    bookMarkCount: 6,
    members: [
      {
        id: 'b1634',
        email: 'asdf@asdf.com',
        nickname: 'asdf',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/arthur.svg`,
        provider: 'link-gather',
        type: 'leader',
      },
      {
        id: 'vaetrvt3',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: '3vya5',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'bu6d4',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'ind75',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'productManager',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
    ],
  },
  {
    id: '1xrde2',
    title: '제목',
    description: 'asdfasdf',
    period: 3,
    stacks: [1, 2, 3, 4],
    purpose: 'business',
    status: 'finish',
    leaderJob: 'backendDeveloper',
    recruitMember: {
      frontendDeveloper: 5,
      backendDeveloper: 5,
      designer: 5,
      productManager: 5,
    },
    bookMarkCount: 1,
    members: [
      {
        id: 'bwu64',
        email: 'asdf@asdf.com',
        nickname: 'asdf',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/arthur.svg`,
        provider: 'link-gather',
        type: 'leader',
      },
      {
        id: 'dseyfr45',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'drjxy',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'rjdy6',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'gl78',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
    ],
  },
  {
    id: 'agwe3',
    title: '제목',
    description: 'asdfasdf',
    period: 3,
    stacks: [1, 2, 3, 4],
    purpose: 'business',
    status: 'progressing',
    leaderJob: 'backendDeveloper',
    recruitMember: {
      frontendDeveloper: 5,
      backendDeveloper: 5,
      designer: 5,
      productManager: 5,
    },
    bookMarkCount: 1,
    members: [
      {
        id: 'hsetr4',
        email: 'asdf@asdf.com',
        nickname: 'asdf',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/arthur.svg`,
        provider: 'link-gather',
        type: 'leader',
      },
      {
        id: 'tdjy7',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'lf78',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'ywdef4',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
      {
        id: 'haers5',
        email: 'asdfg@asdf.com',
        nickname: 'asdfg',
        job: 'backendDeveloper',
        profileImage: `${S3_IMAGE_BUCKET}/duhong.svg`,
        provider: 'link-gather',
        type: 'member',
      },
    ],
  },
];
