export const stacks = [
  { id: 1, name: 'swift', length: 1 },
  { id: 2, name: 'css3', length: 1 },
  { id: 3, name: 'Kotlin', length: 1 },
  { id: 4, name: 'svelte', length: 1 },
  { id: 5, name: 'css', length: 1 },
  { id: 6, name: 'Flutter', length: 2 },
  { id: 7, name: 'swiftUI', length: 2 },
  { id: 8, name: 'React Native', length: 2 },
  { id: 9, name: 'Unity', length: 1 },
  { id: 10, name: 'React', length: 1 },
  { id: 11, name: 'Next.js', length: 2 },
  { id: 12, name: 'Blazor', length: 1 },
  { id: 13, name: 'Electron', length: 2 },
  { id: 14, name: 'Redux', length: 1 },
  { id: 15, name: 'GraphQL', length: 2 },
  { id: 16, name: 'VueJS', length: 1 },
  { id: 17, name: 'Vuex', length: 1 },
  { id: 18, name: 'Relay', length: 1 },
  { id: 19, name: 'Mobx', length: 1 },
  { id: 20, name: 'Angular', length: 2 },
  { id: 21, name: 'Recoil', length: 1 },
  { id: 22, name: 'Storybook', length: 2 },
  { id: 23, name: 'OpenGL', length: 1 },
  { id: 24, name: 'Styled-Component', length: 3 },
  { id: 25, name: 'React Query', length: 2 },
  { id: 26, name: 'ExpressJS', length: 2 },
  { id: 27, name: 'ReactiveX', length: 2 },
  { id: 28, name: 'BackboneJS', length: 2 },
  { id: 29, name: 'Zustand', length: 2 },
  { id: 30, name: 'Emotion', length: 2 },
  { id: 31, name: 'Jotai', length: 1 },
  { id: 32, name: 'jquery', length: 1 },
  { id: 33, name: 'Google Adsense', length: 2 },
  { id: 34, name: 'ES6', length: 1 },
  { id: 35, name: 'Saga', length: 1 },
  { id: 36, name: 'React Hooks API', length: 3 },
  { id: 37, name: 'Tailwind CSS', length: 2 },
  { id: 38, name: 'WebGL', length: 1 },
  { id: 39, name: 'RxSwift', length: 2 },
  { id: 40, name: 'RxJava', length: 1 },
  { id: 41, name: 'Jetpack', length: 2 },
  { id: 42, name: 'Material UI', length: 2 },
  { id: 43, name: 'Jest', length: 1 },
  { id: 44, name: 'RxJS', length: 1 },
  { id: 45, name: 'Redux Toolkit', length: 2 },
  { id: 46, name: 'Redux Thunk', length: 2 },
  { id: 47, name: 'react-sweet-state', length: 3 },
  { id: 48, name: 'Sass', length: 1 },
  { id: 49, name: 'Spring WebFlux', length: 2 },
  { id: 50, name: 'SCSS', length: 1 },
  { id: 51, name: 'Less.js', length: 2 },
  { id: 52, name: 'Docker', length: 1 },
  { id: 53, name: 'Kubernetes', length: 2 },
  { id: 54, name: 'Github', length: 1 },
  { id: 55, name: 'Jenkins', length: 2 },
  { id: 56, name: 'Harnor', length: 1 },
  { id: 57, name: 'Traefik', length: 2 },
  { id: 58, name: 'Github Actions', length: 2 },
  { id: 59, name: 'Istio', length: 1 },
  { id: 60, name: 'Argo CD', length: 2 },
  { id: 61, name: 'OpenEBS', length: 2 },
  { id: 62, name: 'Jaeger', length: 1 },
  { id: 63, name: 'Capistrano', length: 2 },
  { id: 64, name: 'Go CD', length: 1 },
  { id: 65, name: 'Rundeck', length: 2 },
  { id: 66, name: 'Vault', length: 1 },
  { id: 67, name: 'Helm', length: 1 },
  { id: 68, name: 'Ansible', length: 2 },
  { id: 69, name: 'Cricle CI', length: 2 },
  { id: 70, name: 'Central Dogma', length: 2 },
  { id: 71, name: 'Spinnaker', length: 2 },
  { id: 72, name: 'Harbor', length: 1 },
  { id: 73, name: 'Terraform', length: 2 },
  { id: 74, name: 'Gitlab', length: 1 },
  { id: 75, name: 'AWS CodeDeploy', length: 2 },
  { id: 76, name: 'Circle CI', length: 2 },
  { id: 77, name: 'Saltstack', length: 2 },
  { id: 78, name: 'Zabbix', length: 1 },
  { id: 79, name: 'Gulp', length: 1 },
  { id: 80, name: 'Envoy', length: 1 },
  { id: 81, name: 'Datadog', length: 2 },
  { id: 82, name: 'Sentry', length: 1 },
  { id: 83, name: 'Asana', length: 1 },
  { id: 84, name: 'bitbucket', length: 2 },
  { id: 85, name: 'CloudWatch', length: 2 },
  { id: 86, name: 'Google Cloud Deploy', length: 3 },
  { id: 87, name: 'Gradle', length: 1 },
  { id: 88, name: 'AWS CloudFormation', length: 3 },
  { id: 89, name: 'Webpack', length: 2 },
  { id: 90, name: 'SWC', length: 1 },
  { id: 91, name: 'Yarn Berry', length: 2 },
  { id: 92, name: 'Vite', length: 1 },
  { id: 93, name: 'AWS CloudFront', length: 2 },
  { id: 94, name: 'AWS CodeBuild', length: 2 },
  { id: 95, name: 'GitHub Workflow', length: 3 },
  { id: 96, name: 'Git Flow', length: 2 },
  { id: 97, name: 'Babel', length: 1 },
  { id: 98, name: 'Parcel', length: 1 },
  { id: 99, name: 'Codecov', length: 2 },
  { id: 100, name: 'Trello', length: 1 },
  { id: 101, name: 'Jira', length: 1 },
  { id: 102, name: 'Google Docs', length: 2 },
  { id: 103, name: 'Notion', length: 1 },
  { id: 104, name: 'Confluence', length: 2 },
  { id: 105, name: 'SQL', length: 1 },
  { id: 106, name: 'NoSQL', length: 1 },
  { id: 107, name: 'MySQL', length: 1 },
  { id: 108, name: 'MongoDB', length: 2 },
  { id: 109, name: 'PostgreSQL', length: 2 },
  { id: 110, name: 'Google Analytics', length: 3 },
  { id: 111, name: 'Mixpanel', length: 2 },
  { id: 112, name: 'Figma', length: 1 },
  { id: 113, name: 'Adobe XD', length: 2 },
  { id: 114, name: 'Axure', length: 1 },
  { id: 115, name: 'nVision', length: 2 },
  { id: 116, name: 'Marvel', length: 1 },
  { id: 117, name: 'Swagger', length: 2 },
  { id: 118, name: 'Postman', length: 2 },
  { id: 119, name: 'Optimizely', length: 2 },
  { id: 120, name: 'Google Optimize', length: 3 },
  { id: 121, name: 'Tableau', length: 2 },
  { id: 122, name: 'Power BI', length: 2 },
  { id: 123, name: 'Google Data Studio', length: 3 },
  { id: 124, name: 'Slack', length: 1 },
  { id: 125, name: 'Discord', length: 2 },
  { id: 126, name: 'Gathertown', length: 2 },
  { id: 127, name: 'Zoom', length: 1 },
  { id: 128, name: 'Google Meet', length: 2 },
  { id: 129, name: 'Adobe Illustration', length: 3 },
  { id: 130, name: 'Adobe Photoshop', length: 3 },
  { id: 131, name: 'Adobe Indesign', length: 2 },
  { id: 132, name: 'Adobe Aftereffect', length: 3 },
  { id: 133, name: 'Adobe Premiere', length: 2 },
  { id: 134, name: 'Adobe Lightroom', length: 3 },
  { id: 135, name: 'Sketch', length: 1 },
  { id: 136, name: 'Framer', length: 1 },
  { id: 137, name: 'Protopie', length: 2 },
  { id: 138, name: 'Zeplin', length: 1 },
  { id: 139, name: '3Ds MAX', length: 2 },
  { id: 140, name: 'Maya', length: 1 },
  { id: 141, name: 'ZBrush', length: 1 },
  { id: 142, name: 'Artec Studio', length: 2 },
  { id: 143, name: 'Freeform', length: 2 },
  { id: 144, name: '3DCoat', length: 1 },
  { id: 145, name: 'Blender', length: 2 },
  { id: 146, name: 'Wings 3D', length: 2 },
  { id: 147, name: 'Meshmixer', length: 2 },
  { id: 148, name: 'Cinema 4D', length: 2 },
  { id: 149, name: 'Sketch UP', length: 2 },
  { id: 150, name: 'AWS S3', length: 1 },
  { id: 151, name: 'Apache Spark', length: 2 },
  { id: 152, name: 'Apache Kafka', length: 2 },
  { id: 153, name: 'Microsoft SQL Server', length: 3 },
  { id: 154, name: 'NGINX', length: 1 },
  { id: 155, name: 'Git', length: 1 },
  { id: 156, name: 'Puppet', length: 1 },
  { id: 157, name: 'Elasticsearch', length: 2 },
  { id: 158, name: 'Apache Hadoop', length: 2 },
  { id: 159, name: 'Amazon RDS', length: 2 },
  { id: 160, name: 'Apache Cassandra', length: 3 },
  { id: 161, name: 'Microsoft Azure', length: 3 },
  { id: 162, name: 'Google Cloud Platform', length: 3 },
  { id: 163, name: 'Chef', length: 1 },
  { id: 164, name: 'SaltStack', length: 2 },
  { id: 165, name: 'RabbitMQ', length: 2 },
  { id: 166, name: 'Redis', length: 1 },
  { id: 167, name: 'Consul', length: 1 },
  { id: 168, name: 'Grafana', length: 2 },
  { id: 169, name: 'Prometheus', length: 2 },
  { id: 170, name: 'Graylog', length: 2 },
  { id: 171, name: 'Splunk', length: 1 },
  { id: 172, name: 'AWS Lambda', length: 2 },
  { id: 173, name: 'AWS EC2', length: 2 },
  { id: 174, name: 'AWS Elastic Beanstalk', length: 3 },
  { id: 175, name: 'AWS DynamoDB', length: 2 },
  { id: 176, name: 'AWS CloudWatch', length: 2 },
  { id: 177, name: 'AWS Route 53', length: 2 },
  { id: 178, name: 'AWS Elastic Load Balancer', length: 3 },
  { id: 179, name: 'Azure App Service', length: 3 },
  { id: 180, name: 'Azure Cosmos DB', length: 3 },
  { id: 181, name: 'Azure Functions', length: 3 },
  { id: 182, name: 'Azure Kubernetes Service', length: 3 },
  { id: 183, name: 'Azure DevOps', length: 2 },
  { id: 184, name: 'Google Kubernetes Engine', length: 3 },
  { id: 185, name: 'Google Cloud Storage', length: 3 },
  { id: 186, name: 'Google Cloud SQL', length: 3 },
  { id: 187, name: 'Google Cloud Functions', length: 3 },
  { id: 188, name: 'Google Cloud Pub/Sub', length: 3 },
  { id: 189, name: 'Google Cloud Logging', length: 3 },
  { id: 190, name: 'Apache Tomcat', length: 2 },
  { id: 191, name: 'Apache HTTP Server', length: 3 },
  { id: 192, name: 'HAProxy', length: 2 },
  { id: 193, name: 'Varnish Cache', length: 2 },
  { id: 194, name: 'OpenStack', length: 2 },
  { id: 195, name: 'Xen', length: 1 },
  { id: 196, name: 'KVM', length: 1 },
  { id: 197, name: 'VMware vSphere', length: 2 },
  { id: 198, name: 'Microsoft Hyper-V', length: 3 },
  { id: 199, name: 'Oracle VirtualBox', length: 3 },
  { id: 200, name: 'Proxmox VE', length: 2 },
  { id: 201, name: 'FreeBSD', length: 2 },
  { id: 202, name: 'CentOS', length: 1 },
  { id: 203, name: 'Debian', length: 1 },
  { id: 204, name: 'Ubuntu', length: 1 },
  { id: 205, name: 'Red Hat Enterprise Linux', length: 3 },
  { id: 206, name: 'Microsoft Windows Server', length: 3 },
  { id: 207, name: 'Apache ActiveMQ', length: 3 },
  { id: 208, name: 'Apache NiFi', length: 2 },
  { id: 209, name: 'Apache ZooKeeper', length: 3 },
  { id: 210, name: 'InfluxDB', length: 2 },
  { id: 211, name: 'Telegraf', length: 2 },
  { id: 212, name: 'Chronograf', length: 2 },
  { id: 213, name: 'Oracle Database', length: 3 },
  { id: 214, name: 'Couchbase', length: 2 },
  { id: 215, name: 'MariaDB', length: 2 },
  { id: 216, name: 'Neo4j', length: 1 },
  { id: 217, name: 'Apache Lucene', length: 2 },
  { id: 218, name: 'Solr', length: 1 },
  { id: 219, name: 'Logstash', length: 2 },
  { id: 220, name: 'Kibana', length: 1 },
  { id: 221, name: 'Apache Flink', length: 2 },
  { id: 222, name: 'Apache Beam', length: 2 },
  { id: 223, name: 'Apache Apex', length: 2 },
  { id: 224, name: 'Apache Storm', length: 2 },
  { id: 225, name: 'Apache Flume', length: 2 },
  { id: 226, name: 'Apache Sqoop', length: 2 },
  { id: 227, name: 'Apache Oozie', length: 2 },
  { id: 228, name: 'Apache Airflow', length: 2 },
  { id: 229, name: 'Apache Samza', length: 2 },
  { id: 230, name: 'Apache Zeppelin', length: 3 },
  { id: 231, name: 'Apache Ranger', length: 2 },
  { id: 232, name: 'Apache Atlas', length: 2 },
  { id: 233, name: 'Apache Knox', length: 2 },
  { id: 234, name: 'Apache Nifi Registry', length: 3 },
  { id: 235, name: 'Apache Metron', length: 2 },
  { id: 236, name: 'Apache Calcite', length: 2 },
  { id: 237, name: 'Apache Trafodion', length: 3 },
  { id: 238, name: 'HTML', length: 1 },
  { id: 239, name: 'CSS', length: 1 },
  { id: 240, name: 'JavaScript', length: 2 },
  { id: 241, name: 'TypeScript', length: 2 },
  { id: 242, name: 'React JSX', length: 2 },
  { id: 243, name: 'Less', length: 1 },
  { id: 244, name: 'CoffeeScript', length: 2 },
  { id: 245, name: 'Dart', length: 1 },
  { id: 246, name: 'Lua', length: 1 },
  { id: 247, name: 'Haxe', length: 1 },
  { id: 248, name: 'ReasonML', length: 2 },
  { id: 249, name: 'ClojureScript', length: 2 },
  { id: 250, name: 'PureScript', length: 2 },
  { id: 251, name: 'Scala.js', length: 2 },
  { id: 252, name: 'Kotlin JS', length: 2 },
  { id: 253, name: 'Vue.js', length: 1 },
  { id: 254, name: 'Nuxt.js', length: 2 },
  { id: 255, name: 'Ember.js', length: 2 },
  { id: 256, name: 'Backbone.js', length: 2 },
  { id: 257, name: 'Polymer', length: 2 },
  { id: 258, name: 'Aurelia', length: 2 },
  { id: 259, name: 'Meteor', length: 1 },
  { id: 260, name: 'Svelte', length: 1 },
  { id: 261, name: 'Stencil', length: 2 },
  { id: 262, name: 'SvelteKit', length: 2 },
  { id: 263, name: 'Stimulus', length: 2 },
  { id: 264, name: 'Alpine.js', length: 2 },
  { id: 265, name: 'Mithril', length: 2 },
  { id: 266, name: 'Riot.js', length: 2 },
  { id: 267, name: 'Marko', length: 1 },
  { id: 268, name: 'Hyperapp', length: 2 },
  { id: 269, name: 'Choo', length: 1 },
  { id: 270, name: 'Ractive.js', length: 2 },
  { id: 271, name: 'Inferno', length: 2 },
  { id: 272, name: 'Grunt', length: 1 },
  { id: 273, name: 'Rollup', length: 1 },
  { id: 274, name: 'Brunch', length: 1 },
  { id: 275, name: 'Browserify', length: 2 },
  { id: 276, name: 'Snowpack', length: 2 },
  { id: 277, name: 'FuseBox', length: 2 },
  { id: 278, name: 'NPM', length: 1 },
  { id: 279, name: 'Yarn', length: 1 },
  { id: 280, name: 'PostCSS', length: 2 },
  { id: 281, name: 'webpack-dev-server', length: 3 },
  { id: 282, name: 'BrowserSync', length: 2 },
  { id: 283, name: 'Create React App', length: 3 },
  { id: 284, name: 'Expo', length: 1 },
  { id: 285, name: 'Broccoli', length: 2 },
  { id: 286, name: 'Fly', length: 1 },
  { id: 287, name: 'Poi', length: 1 },
  { id: 288, name: 'WMR', length: 1 },
  { id: 289, name: 'Lume', length: 1 },
  { id: 290, name: 'Java', length: 1 },
  { id: 291, name: 'Python', length: 1 },
  { id: 292, name: 'PHP', length: 1 },
  { id: 293, name: 'Ruby', length: 1 },
  { id: 294, name: 'C#', length: 1 },
  { id: 295, name: 'Go', length: 1 },
  { id: 296, name: 'Swift', length: 1 },
  { id: 297, name: 'Scala', length: 1 },
  { id: 298, name: 'Rust', length: 1 },
  { id: 299, name: 'Perl', length: 1 },
  { id: 300, name: 'Objective-C', length: 2 },
  { id: 301, name: 'Shell', length: 1 },
  { id: 302, name: 'C++', length: 1 },
  { id: 303, name: 'Groovy', length: 1 },
  { id: 304, name: 'R', length: 1 },
  { id: 305, name: 'Haskell', length: 2 },
  { id: 306, name: 'Erlang', length: 1 },
  { id: 307, name: 'Clojure', length: 2 },
  { id: 308, name: 'F#', length: 1 },
  { id: 309, name: 'Julia', length: 1 },
  { id: 310, name: 'Crystal', length: 2 },
  { id: 311, name: 'Elixir', length: 1 },
  { id: 312, name: 'OCaml', length: 1 },
  { id: 313, name: 'Scheme', length: 1 },
  { id: 314, name: 'Spring', length: 1 },
  { id: 315, name: 'Spring Boot', length: 2 },
  { id: 316, name: 'Express.js', length: 2 },
  { id: 317, name: 'Django', length: 1 },
  { id: 318, name: 'Ruby on Rails', length: 2 },
  { id: 319, name: 'Laravel', length: 2 },
  { id: 320, name: 'Flask', length: 1 },
  { id: 321, name: 'ASP.NET', length: 2 },
  { id: 322, name: 'Play Framework', length: 2 },
  { id: 323, name: 'Symfony', length: 2 },
  { id: 324, name: 'Nest.js', length: 2 },
  { id: 325, name: 'Gin', length: 1 },
  { id: 326, name: 'Koa', length: 1 },
  { id: 327, name: 'Ktor', length: 1 },
  { id: 328, name: 'Echo', length: 1 },
  { id: 329, name: 'Phoenix', length: 2 },
  { id: 330, name: 'FastAPI', length: 2 },
  { id: 331, name: 'Vapor', length: 1 },
  { id: 332, name: 'Akka', length: 1 },
  { id: 333, name: 'Rocket', length: 1 },
  { id: 334, name: 'Hapi', length: 1 },
  { id: 335, name: 'Spark', length: 1 },
  { id: 336, name: 'LoopBack', length: 2 },
  { id: 337, name: 'Sails.js', length: 2 },
  { id: 338, name: 'Mojolicious', length: 2 },
  { id: 339, name: 'Grails', length: 1 },
  { id: 340, name: 'Dropwizard', length: 2 },
  { id: 341, name: 'Ratpack', length: 2 },
  { id: 342, name: 'Micronaut', length: 2 },
  { id: 343, name: 'AdonisJS', length: 2 },
  { id: 344, name: 'CakePHP', length: 2 },
  { id: 345, name: 'Ginatra', length: 2 },
];
